import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "./logout";

export const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-green-950">
          {!!session && <div className="flex gap-10"><Link className="bg-red-950" href="/">
                home
              </Link><Logout /></div>}
          {!session && (
            <div className="flex gap-10">
              <Link className="bg-red-950" href="/">
                home
              </Link>
              <Link className="bg-red-950" href="/login">
                login
              </Link>
              <Link className="bg-red-950" href={`/register`}>
                register
              </Link>
            </div>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
